# Generated by Django 4.0.4 on 2022-05-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo_url',
        ),
    ]
