# Generated by Django 4.0.4 on 2022-05-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_remove_review_photo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
