# Generated by Django 4.0.4 on 2022-05-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bike.path'),
        ),
    ]
