# Generated by Django 4.0.4 on 2022-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_alter_review_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
